ajuste coverage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,11 +26,12 @@ jobs:
 
     - name: Check Coverage
       run: |
-        COVERAGE=$(cat coverage/coverage-final.json | jq '.total.lines.pct')
-        if [ "$COVERAGE" -lt 80 ]; then
-          echo "Coverage ($COVERAGE%) is below the threshold (80%)"
-          exit 1
-        fi  
+        COVERAGE=$(npx jest --coverage --silent | grep 'All files' | awk '{print $4}' | sed 's/%//')
+          echo "Coverage: $COVERAGE%"
+          if [ "$COVERAGE" -lt 80 ]; then
+            echo "Coverage is below 80%. Failing the job."
+            exit 1
+          fi
 
     - name: SonarCloud Analysis
       env:
